INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (10, '日産', 1, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (20, 'トヨタ', 2, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (30, 'ホンダ', 3, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (40, '三菱', 4, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (50, 'マツダ', 5, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (60, 'スバル', 6, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (70, 'いすゞ', 7, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (80, 'スズキ', 8, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (85, 'ダイハツ', 9, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (90, '輸入車', 10, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (95, 'その他', 11, false);
INSERT INTO maker (maker_id, maker_name, display_order, del_flg) VALUES (99, '保有なし', 12, false);


INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (1, 'アベニール', 10, 1, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (2, 'インフィニティ', 10, 2, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (3, 'ウイングロード', 10, 3, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (4, 'エクストレイル', 10, 4, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (5, 'オッティ', 10, 5, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (6, 'Ｓ－ＲＶ', 10, 6, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (7, 'ＮＶ200バネット', 10, 7, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (8, 'エルグランド', 10, 8, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (9, 'オースター', 10, 9, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (10, 'キックス', 10, 10, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (11, 'キャラバンコーチ', 10, 11, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (12, 'キューブ', 10, 12, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (13, 'キューブキュービック', 10, 13, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (14, 'クルー', 10, 14, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (15, 'クリッパー', 10, 15, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (16, 'クリッパーリオ', 10, 16, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (17, 'グロリア', 10, 17, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (18, 'サニー', 10, 18, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (19, 'サファリ', 10, 19, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (20, 'サンタナ', 10, 20, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (21, 'シーマ', 10, 21, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (22, 'シルビア', 10, 22, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (23, 'ジューク', 10, 23, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (24, 'スカイライン', 10, 24, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (25, 'スカイラインクーペ', 10, 25, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (26, 'スカイラインクロスオーバー', 10, 26, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (27, 'スタンザ', 10, 27, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (28, 'ステージア', 10, 28, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (29, 'セドリック', 10, 29, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (30, 'セフィーロ', 10, 30, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (31, 'セフィーロワゴン', 10, 31, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (32, 'セレナ', 10, 32, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (33, 'ティアナ', 10, 33, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (34, 'ティーダ', 10, 34, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (35, 'ティーダ ラティオ', 10, 35, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (36, 'ティーノ', 10, 36, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (37, 'デュアリス', 10, 37, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (38, 'テラノ', 10, 38, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (39, 'ノート', 10, 39, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (40, 'バサラ', 10, 40, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (41, 'バネットコーチ', 10, 41, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (42, 'パルサー', 10, 42, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (43, 'Ｂｅ-１・パオ・フィガロ', 10, 43, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (44, 'PINO', 10, 44, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (45, 'フーガ', 10, 45, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (46, 'フェアレディＺ', 10, 46, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (47, 'プリメーラ／カミノ', 10, 47, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (48, 'プリメーラ／カミノ　ワゴン', 10, 48, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (49, 'ブルーバード', 10, 49, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (50, 'ブルーバードシルフィ', 10, 50, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (51, 'プレーリー', 10, 51, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (52, 'プレサージュ', 10, 52, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (53, 'プレジデント', 10, 53, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (54, 'プレセア', 10, 54, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (55, 'ホーミーコーチ', 10, 55, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (56, 'マーチ', 10, 56, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (57, 'マイクラC+C', 10, 57, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (58, 'マキシマ', 10, 58, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (59, 'ミストラル', 10, 59, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (60, 'ムラーノ', 10, 60, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (61, 'モコ', 10, 61, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (62, 'ラシーン', 10, 62, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (63, 'ラフェスタ', 10, 63, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (64, 'ラフェスタ ハイウェイスター', 10, 64, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (65, 'ラルゴ', 10, 65, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (66, 'ラングレー', 10, 66, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (67, 'リーフ', 10, 67, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (68, 'リバティ', 10, 68, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (69, 'リベルタビラ', 10, 69, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (70, 'ルークス', 10, 70, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (71, 'ルキノ', 10, 71, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (72, 'ルネッサ', 10, 72, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (73, 'レグラス', 10, 73, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (74, 'レパード', 10, 74, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (75, 'ローレル', 10, 75, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (76, 'ローレルスピリット', 10, 76, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (77, '１８０ＳＸ', 10, 77, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (78, 'ＡＤバン', 10, 78, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (79, 'GT-R', 10, 79, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (80, 'アトラス', 10, 80, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (81, 'アベニールカーゴ', 10, 81, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (82, 'エキスパート', 10, 82, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (83, 'エスカルゴ', 10, 83, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (84, 'キャラバン　バン', 10, 84, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (85, 'グロリアバン', 10, 85, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (86, 'コンドル', 10, 86, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (87, 'サニートラック', 10, 87, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (88, 'シビリアン', 10, 88, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (89, 'スカイラインバン', 10, 89, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (90, 'セドリックバン', 10, 90, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (91, 'セレナカーゴ', 10, 91, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (92, 'ダットサントラック', 10, 92, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (93, 'バネットトラック', 10, 93, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (94, 'バネットバン', 10, 94, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (95, 'ブルーバードバン', 10, 95, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (96, 'プレーリーバン', 10, 96, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (97, 'ホーミーバン', 10, 97, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (98, 'その他', 10, 98, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (99, 'アイシス', 20, 99, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (100, 'アベンシス', 20, 100, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (101, 'アリオン', 20, 101, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (102, 'アリスト', 20, 102, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (103, 'アルテッツァ', 20, 103, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (104, 'アルファード', 20, 104, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (105, 'アレックス', 20, 105, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (106, 'イスト', 20, 106, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (107, 'イプサム', 20, 107, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (108, 'ＷＩＬＬ ＶＩ', 20, 108, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (109, 'ＷＩＬＬ ＶS', 20, 109, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (110, 'ＷＩＬＬ サイファ', 20, 110, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (111, 'ウィッシュ', 20, 111, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (112, 'ヴィッツ', 20, 112, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (113, 'ウィンダム', 20, 113, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (114, 'ヴェルファイア', 20, 114, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (115, 'ヴェロッサ', 20, 115, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (116, 'ヴォクシー', 20, 116, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (117, 'ヴォルツ', 20, 117, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (118, 'エスティマ', 20, 118, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (119, 'エスティマエミーナ', 20, 119, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (120, 'エスティマルシーダ', 20, 120, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (121, 'ＭＲ－Ｓ', 20, 121, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (122, 'ＭＲ２', 20, 122, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (123, 'オーパ', 20, 123, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (124, 'オーリス', 20, 124, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (125, 'オリジン', 20, 125, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (126, 'ガイア', 20, 126, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (127, 'カムリ', 20, 127, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (128, 'カムリ／ビスタ', 20, 128, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (129, 'カムリグラシア', 20, 129, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (130, 'カリーナ', 20, 130, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (131, 'カリブ', 20, 131, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (132, 'カルディナ', 20, 132, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (133, 'カルディナワゴン', 20, 133, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (134, 'カレン', 20, 134, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (135, 'カローラ', 20, 135, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (136, 'カローラII', 20, 136, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (137, 'カローラスパシオ', 20, 137, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (138, 'カローラセレス', 20, 138, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (139, 'カローラフィールダー', 20, 139, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (140, 'カローラランクス', 20, 140, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (141, 'カローラルミオン', 20, 141, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (142, 'カローラワゴン', 20, 142, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (143, 'キャミ', 20, 143, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (144, 'クイックデリバリー', 20, 144, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (145, 'クラウン', 20, 145, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (146, 'クラウンエステート', 20, 146, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (147, 'クラウンコンフォート', 20, 147, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (148, 'クラウンバン', 20, 148, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (149, 'クラウンマジェスタ', 20, 149, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (150, 'グランドハイエース', 20, 150, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (151, 'グランビア', 20, 151, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (152, 'クルーガー', 20, 152, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (153, 'クレスタ', 20, 153, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (154, 'コルサ', 20, 154, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (155, 'コロナ', 20, 155, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (156, 'コロナプレミオ', 20, 156, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (157, 'コンフォート', 20, 157, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (158, 'サイノス', 20, 158, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (159, 'シエンタ', 20, 159, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (160, 'サクシード', 20, 160, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (161, 'スープラ', 20, 161, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (162, 'スターレット', 20, 162, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (163, 'スパシオ', 20, 163, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (164, 'スプリンター', 20, 164, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (165, 'スプリンタートレノ', 20, 165, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (166, 'スプリンターマリノ', 20, 166, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (167, 'スプリンターワゴン', 20, 167, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (168, 'セプターセダン', 20, 168, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (169, 'セプターワゴン', 20, 169, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (170, 'セラ', 20, 170, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (171, 'セリカ', 20, 171, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (172, 'セルシオ', 20, 172, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (173, 'センチュリー', 20, 173, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (174, 'ソアラ', 20, 174, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (175, 'ターセル', 20, 175, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (176, 'ダイナ・トヨエース10', 20, 176, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (177, 'ダイナ10・20', 20, 177, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (178, 'チェイサー', 20, 178, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (179, 'ツーリングハイエース', 20, 179, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (180, 'デュエット', 20, 180, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (181, 'トヨエース10・20', 20, 181, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (182, 'ナディア', 20, 182, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (183, 'ハイエース', 20, 183, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (184, 'ノア', 20, 184, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (185, 'ハイエースレジアス', 20, 185, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (186, 'ハイラックス', 20, 186, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (187, 'ハイラックスサーフ', 20, 187, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (188, 'ハリアー', 20, 188, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (189, 'パッソ', 20, 189, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (190, 'ピクシススペース', 20, 190, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (191, 'ビスタアルデオ', 20, 191, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (192, 'ビスタワゴン', 20, 192, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (193, 'ＢＢ', 20, 193, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (194, 'ファンカーゴ', 20, 194, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (195, 'プラッツ', 20, 195, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (196, 'プリウス', 20, 196, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (197, 'ブレイド', 20, 197, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (198, 'ブレビス', 20, 198, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (199, 'プレミオ', 20, 199, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (200, 'プログレ', 20, 200, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (201, 'プロナード', 20, 201, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (202, 'プロボックス', 20, 202, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (203, 'ベルタ', 20, 203, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (204, 'ポルテ', 20, 204, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (205, 'マーク X', 20, 205, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (206, 'マークII', 20, 206, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (207, 'マークII ワゴン', 20, 207, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (208, 'ラウム', 20, 208, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (209, 'ラクテイス', 20, 209, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (210, 'ラッシュ', 20, 210, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (211, 'ＲＡＶ４', 20, 211, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (212, 'ランドクルーザー', 20, 212, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (213, 'レジアスエース', 20, 213, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (214, 'レクサス', 20, 214, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (215, 'レジアスエースバン', 20, 215, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (216, 'カリーナバン', 20, 216, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (217, 'カルディナバン', 20, 217, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (218, 'カローラバン(ｽﾌﾟﾘﾝﾀｰﾊﾞﾝ)', 20, 218, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (219, 'コースター', 20, 219, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (220, 'コロナバン', 20, 220, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (221, 'スターレットバン', 20, 221, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (222, 'タウンエース', 20, 222, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (223, 'パブリカトラック', 20, 223, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (224, 'マーク X', 20, 224, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (225, 'マークⅡ', 20, 225, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (226, 'マークII バン', 20, 226, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (227, 'マスターエース', 20, 227, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (228, 'ライトエース', 20, 228, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (229, 'その他', 20, 229, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (230, 'アヴァンシア', 30, 230, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (231, 'アコード', 30, 231, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (232, 'アコードワゴン', 30, 232, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (233, 'ＥＶプラス', 30, 233, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (234, 'インサイト', 30, 234, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (235, 'インスパイア', 30, 235, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (236, 'インテグラ（クイント）', 30, 236, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (237, 'インテグラ（新）', 30, 237, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (238, 'インテグラＳＪ', 30, 238, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (239, 'Ｓ－ＭＸ', 30, 239, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (240, 'エアウエイブ', 30, 240, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (241, 'エディックス', 30, 241, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (242, 'エリシオン', 30, 242, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (243, 'Ｓ２０００', 30, 243, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (244, 'ＨＲ－Ｖ', 30, 244, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (245, 'ＮＳＸ', 30, 245, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (246, 'オデッセイ', 30, 246, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (247, 'オルティア', 30, 247, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (248, 'キャパ', 30, 248, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (249, 'クロスロード', 30, 249, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (250, 'コンチェルト', 30, 250, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (251, 'ＣＲ－Ｖ', 30, 251, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (252, 'シティ', 30, 252, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (253, 'シビック／ＣＲ-Ｘ', 30, 253, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (254, 'シビックフェリオ', 30, 254, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (255, 'ジャズ', 30, 255, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (256, 'ステップワゴン', 30, 256, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (257, 'ストリーム', 30, 257, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (258, 'セイバー', 30, 258, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (259, 'ドマーニ', 30, 259, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (260, 'トルネオ', 30, 260, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (261, 'ビガー', 30, 261, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (262, 'フィット', 30, 262, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (263, 'フリード（4・5人乗り）', 30, 263, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (264, 'フリード（7・8人乗り）', 30, 264, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (265, 'プレリュード', 30, 265, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (266, 'ホライゾン', 30, 266, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (267, 'モビリオ', 30, 267, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (268, 'モビリオスパイク', 30, 268, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (269, 'ラグレイト', 30, 269, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (270, 'ラファーガ／アスコット', 30, 270, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (271, 'レジェンド', 30, 271, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (272, 'ローバースターリング', 30, 272, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (273, 'ロゴ', 30, 273, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (274, 'シビックバン', 30, 274, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (275, 'パートナー', 30, 275, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (276, '軽乗用車', 30, 276, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (277, '軽商用車', 30, 277, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (278, 'その他', 30, 278, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (279, 'アウトランダー', 40, 279, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (280, 'アスパイア', 40, 280, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (281, 'ＲＶＲ', 40, 281, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (282, 'ＦＴＯ', 40, 282, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (283, 'エアトレック', 40, 283, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (284, 'エクスプリ', 40, 284, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (285, 'エメロード', 40, 285, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (286, 'ギャラン（Σ・Λ）', 40, 286, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (287, 'ギャラン（含エテルナ）', 40, 287, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (288, 'キャンター', 40, 288, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (289, 'グランディス', 40, 289, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (290, 'コルト', 40, 290, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (291, 'シャリオ', 40, 291, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (292, 'ＧＴＯ', 40, 292, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (293, 'スタリオン', 40, 293, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (294, 'セディア　ワゴン', 40, 294, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (295, 'タウンボックスワイド', 40, 295, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (296, 'チャレンジャー', 40, 296, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (297, 'ディアマンテ', 40, 297, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (298, 'ディアマンテワゴン', 40, 298, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (299, 'ディオン', 40, 299, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (300, 'ディグニティ', 40, 300, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (301, 'デボネア', 40, 301, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (302, 'デリカ', 40, 302, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (303, 'デリカスペースギア', 40, 303, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (304, 'トッポＢＪワイド', 40, 304, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (305, 'パジェロ', 40, 305, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (306, 'パジェロイオ', 40, 306, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (307, 'パジェロジュニア', 40, 307, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (308, 'ピスタチオ', 40, 308, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (309, 'プラウディア', 40, 309, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (310, 'ミラージュ', 40, 310, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (311, 'ミラージュディンゴ', 40, 311, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (312, 'ランサー', 40, 312, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (313, 'ランサーカーゴ', 40, 313, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (314, 'ランサーセディア', 40, 314, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (315, 'ランサーセディアワゴン', 40, 315, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (316, 'ランサーバン', 40, 316, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (317, 'リベロカーゴ', 40, 317, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (318, 'リベロワゴン', 40, 318, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (319, 'レグナム', 40, 319, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (320, 'ローザ･ジープ･ふそう', 40, 320, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (321, '軽乗用車', 40, 321, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (322, '軽商用車', 40, 322, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (323, 'その他', 40, 323, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (324, 'ＲＸ－７', 50, 324, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (325, 'ＲＸ－８', 50, 325, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (326, 'ｱｸｾﾗ', 50, 326, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (327, 'アクセラ スポーツ', 50, 327, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (328, 'ｱﾃﾝｻﾞ', 50, 328, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (329, 'アテンザワゴン', 50, 329, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (330, 'ＡＺ－３', 50, 330, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (331, 'ＭＳ－８', 50, 331, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (332, 'ＭＸ－６', 50, 332, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (333, 'ＭＰＶ', 50, 333, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (334, 'カペラ（テルスター）', 50, 334, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (335, 'カペラバン', 50, 335, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (336, 'カペラワゴン', 50, 336, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (337, 'クレフ', 50, 337, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (338, 'クロノス（ＭＳ-６）', 50, 338, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (339, 'コスモ（ユーノスコスモ）', 50, 339, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (340, 'CX-7', 50, 340, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (341, 'センティア（ＭＳ-９）', 50, 341, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (342, 'タイタン', 50, 342, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (343, 'デミオ', 50, 343, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (344, 'トリビュート', 50, 344, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (345, 'ビアンテ', 50, 345, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (346, 'ファミリア', 50, 346, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (347, 'ファミリア（ﾚｰｻﾞｰ）', 50, 347, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (348, 'ファミリアバン', 50, 348, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (349, 'ファミリアワゴン', 50, 349, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (350, 'フェスティバ', 50, 350, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (351, 'フェスティババン', 50, 351, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (352, 'フリーダ', 50, 352, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (353, 'プレマシー', 50, 353, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (354, 'プロシード（マービー）', 50, 354, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (355, 'プロシードレバンテ', 50, 355, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (356, 'ペリーサ', 50, 356, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (357, 'ペルソナ', 50, 357, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (358, 'ボンゴ', 50, 358, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (359, 'ボンゴフレンディ', 50, 359, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (360, 'ボンゴブローニー', 50, 360, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (361, 'ミレーニア', 50, 361, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (362, 'ユーノス１００', 50, 362, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (363, 'ユーノス３００（ﾕｰﾉｽ500）', 50, 363, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (364, 'ユーノス８００', 50, 364, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (365, 'ユーノスプレッソ', 50, 365, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (366, 'ユーノスロードスター', 50, 366, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (367, 'ランティス', 50, 367, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (368, 'ルーチェ', 50, 368, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (369, 'ルーチェバン', 50, 369, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (370, 'レーザーリデア', 50, 370, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (371, 'レビュー', 50, 371, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (372, '軽乗用車', 50, 372, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (373, '軽商用車', 50, 373, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (374, 'その他', 50, 374, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (375, 'アルシオーネ', 60, 375, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (376, 'インプレッサ', 60, 376, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (377, 'インプレッサワゴン', 60, 377, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (378, 'エクシーガ', 60, 378, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (379, 'ジャスティ', 60, 379, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (380, 'スバルビックホーン', 60, 380, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (381, 'ドミンゴ', 60, 381, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (382, 'トラビック', 60, 382, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (383, 'フォレスター', 60, 383, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (384, 'レオーネ', 60, 384, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (385, 'レオーネバン', 60, 385, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (386, 'レガシィ', 60, 386, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (387, '軽乗用車', 60, 387, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (388, '軽商用車', 60, 388, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (389, 'その他', 60, 389, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (390, 'アスカ', 70, 390, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (391, 'エルフ', 70, 391, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (392, 'コモ', 70, 392, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (393, 'ジェミニ（ＰＡネロ）', 70, 393, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (394, 'ジェミネット', 70, 394, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (395, 'ピアッツア･１１７クーペ', 70, 395, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (396, 'ビークロス', 70, 396, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (397, 'ビックホーン', 70, 397, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (398, 'ファーゴ', 70, 398, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (399, 'ファスター', 70, 399, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (400, 'ミュー', 70, 400, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (401, 'その他', 70, 401, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (402, 'エスクード', 80, 402, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (403, 'SX4', 80, 403, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (404, 'Ｘ－９０', 80, 404, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (405, 'エブリィプラス', 80, 405, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (406, 'エリオ', 80, 406, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (407, 'カルタス', 80, 407, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (408, 'カルタスバン', 80, 408, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (409, 'シボレークルーズ', 80, 409, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (410, 'ジムニー', 80, 410, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (411, 'スイフト', 80, 411, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (412, 'ランディ', 80, 412, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (413, 'ワゴンＲソリオ', 80, 413, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (414, 'ワゴンＲプラス', 80, 414, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (415, 'ワゴンＲワイド', 80, 415, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (416, '軽乗用車', 80, 416, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (417, '軽商用車', 80, 417, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (418, 'その他', 80, 418, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (419, 'アトレーセブン', 85, 419, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (420, 'アプローズ', 85, 420, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (421, 'アルティス', 85, 421, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (422, 'クー', 85, 422, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (423, 'シャルマン', 85, 423, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (424, 'シャレード', 85, 424, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (425, 'ストーリア', 85, 425, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (426, 'タフトラガー', 85, 426, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (427, 'ﾋﾞｰｺﾞ', 85, 427, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (428, 'ﾌﾞｰﾝ', 85, 428, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (429, 'テリオス', 85, 429, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (430, 'デルタ', 85, 430, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (431, 'デルタワイド', 85, 431, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (432, 'パイザー', 85, 432, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (433, 'ハイゼットグランカーゴ', 85, 433, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (434, 'ミラ（1000CC）', 85, 434, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (435, 'ミライース', 85, 435, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (436, 'ロッキー', 85, 436, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (437, 'ＹＲＶ', 85, 437, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (438, '軽乗用車', 85, 438, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (439, '軽商用車', 85, 439, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (440, 'その他', 85, 440, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (441, 'ベンツ ｽﾓｰﾙｸﾗｽ', 90, 441, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (442, 'ベンツ ﾐﾄﾞﾙｸﾗｽ', 90, 442, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (443, 'ベンツ ﾗｰｼﾞｸﾗｽ', 90, 443, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (444, 'ＢＭＷ 3ｼﾘｰｽﾞ', 90, 444, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (445, 'ＢＭＷ 5ｼﾘｰｽﾞ', 90, 445, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (446, 'ＢＭＷ 6ｼﾘｰｽﾞ', 90, 446, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (447, 'ＢＭＷ 7ｼﾘｰｽﾞ', 90, 447, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (448, 'ＢＭＷ 8ｼﾘｰｽﾞ', 90, 448, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (449, 'BMW Mｼﾘｰｽﾞ', 90, 449, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (450, 'ルノー アヴァンタイム', 90, 450, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (451, 'ルノー カングー', 90, 451, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (452, 'ルノー セニック', 90, 452, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (453, 'ルノー トゥインゴ', 90, 453, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (454, 'ルノー メガーヌ', 90, 454, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (455, 'ルノー ラグナ', 90, 455, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (456, 'ルノー ルーテシア', 90, 456, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (457, 'オペル アストラ', 90, 457, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (458, 'オペル ヴィータ', 90, 458, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (459, 'オペル ベクトラ', 90, 459, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (460, 'アウディ', 90, 460, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (461, 'ボルボ', 90, 461, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (462, 'VW', 90, 462, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (463, 'シトロエン', 90, 463, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (464, 'フィアット', 90, 464, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (465, 'プジョー', 90, 465, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (466, 'ローバー(含ミニ)', 90, 466, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (467, 'ジープ', 90, 467, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (468, 'イクシオン', 90, 468, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (469, 'フェスティバワゴン', 90, 469, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (470, 'レーザー', 90, 470, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (471, 'その他 乗用車', 90, 471, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (472, 'その他 商用車', 90, 472, false);
INSERT INTO car (car_id, car_name, maker_id, display_order, del_flg) VALUES (473, 'その他', 95, 473, false);
